---
- name: Build Autoware Control Dependencies
  hosts: localhost
  connection: local
  vars:
    rosdep_install_dependency_types:
      - buildtool
      - buildtool_export
      - build_export
      - build

  roles:
    - role: bounverif.ros.ros2_install
    - role: bounverif.autoware_universe.distro_setup
    - role: bounverif.ros.cuda_toolkit_install
    - role: bounverif.ros.repositories
    - role: bounverif.ros.rosdep_install
